version: "3.9"

services:
  auth_mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$AUTH_MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$AUTH_MONGODB_PASSWORD
    ports:
      - $AUTH_MONGODB_PORT:$AUTH_MONGODB_PORT

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
