[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.10.2"
prost = "0.12"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
grpc-interfaces = { path = "../grpc-interfaces" }
clap =  { version = "4.4.10", features = ["derive", "env"] }
dotenv = "0.15.0"
